// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function SAVGAM()
{

//instance_activate_all()

ini_open(string(global.savee)+"GLOBAL.ini")


ini_write_real("VAR","0",global.owoll)
ini_write_real("VAR","1",global.pogter)
ini_write_real("VAR","2",global.take)
ini_write_real("VAR","3",global.NRDIAL)
ini_write_real("VAR","4",global.grlw)
ini_write_real("VAR","5",global.day)
ini_write_real("VAR","6",global.dork)
ini_write_real("VAR","7",global.zwm)
ini_write_real("VAR","8",global.cie)
ini_write_real("VAR","9",global.zwzb)   
ini_write_real("VAR","10",global.pay)             
ini_write_real("VAR","11",global.dork)              
ini_write_string("VAR","12",global.rozm)               
ini_write_real("VAR","13",global.hour)             
ini_write_real("VAR","14",global.day)             
ini_write_string("VAR","15",global.job)          
ini_write_string("VAR","16",global.inte)      
ini_write_real("VAR","17",global.minute)             
ini_write_real("VAR","18",global.jablka)            
ini_write_real("VAR","19",global.zalrom)            
ini_write_real("VAR","20",global.fug)               
ini_write_real("VAR","21",global.tgo)               
ini_write_real("VAR","22",global.zboze)             
ini_write_real("VAR","23",global.jagody)            
ini_write_real("VAR","24",global.grzyby)            
ini_write_real("VAR","25",global.dwox)             
ini_write_real("VAR","26",global.zloto)             
ini_write_real("VAR","27",global.ryby)             
ini_write_real("VAR","28",global.woda)         
ini_write_real("VAR","29",global.srys)              
ini_write_real("VAR","30",global.cgame)
ini_write_real("VAR","31",global.gamefin)
ini_write_real("VAR","32",global.krold)
ini_write_real("VAR","33",global.magd)
ini_write_real("VAR","34",global.wybmis)
ini_write_real("VAR","35",global.peopatak)
ini_write_real("VAR","36",global.kufopn) 
ini_write_real("VAR","37",global.otb)
ini_write_real("VAR","38",global.skumj)
ini_write_real("VAR","39",global.paczk0)
ini_write_real("VAR","40",global.pr1)
ini_write_real("VAR","41",global.fjask0)
ini_write_real("VAR","42",global.worki)
ini_write_real("VAR","43",global.lkey)
ini_write_real("VAR","44",global.nasi0)
ini_write_real("VAR","45",global.zwmi1)
ini_write_real("VAR","46",global.artef0)
ini_write_real("VAR","47",global.ksiz1)
ini_write_real("VAR","48",global.stmo)
ini_write_real("VAR","49",global.pir)
ini_write_real("VAR","50",global.drems1)
ini_write_real("VAR","51",global.mmp)
ini_write_real("VAR","52",global.zowce)
ini_write_real("VAR","53",global.wor2)
ini_write_real("VAR","54",global.worx1)
//ini_write_string("VAR","55",global.target)
ini_write_real("VAR","56",global.PTer)
ini_write_real("VAR","57",global.bowall1)
ini_write_real("VAR","58",global.b1)
ini_write_real("VAR","59",global.b2)
ini_write_real("VAR","60",global.aczar)
ini_write_real("VAR","61",global.nozs)
ini_write_real("VAR","62",global.zlomiecze)
ini_write_real("VAR","63",global.bdmiecze)
ini_write_real("VAR","64",global.dmiecze)
ini_write_real("VAR","65",global.doluki)
ini_write_real("VAR","66",global.zupy)
ini_write_real("VAR","67",global.umieso)
ini_write_real("VAR","68",global.skory)
ini_write_real("VAR","69",global.zbr1)
ini_write_real("VAR","70",global.zbr2)
ini_write_real("VAR","71",global.zbr3)
ini_write_real("VAR","72",global.smetal)
ini_write_real("VAR","73",global.pulapka)
ini_write_real("VAR","74",global.atakON)
ini_write_real("VAR","75",global.chleb)
ini_write_real("VAR","76",global.jkey)
ini_write_real("VAR","77",global.strdl)
ini_write_real("VAR","78",global.zmiecze)
ini_write_real("VAR","79",global.luki)
ini_write_real("VAR","80",global.ter)
ini_write_real("VAR","81",global.IN)
ini_write_real("VAR","82",global.maata)
ini_write_real("VAR","83",global.tgo)
ini_write_real("VAR","84",global.fug)
ini_write_real("VAR","85",global.mzupa)
ini_write_real("VAR","86",global.smieso)
ini_write_real("VAR","87",global.ryby)
ini_write_real("VAR","88",global.dbax)
ini_write_real("VAR","89",global.dwox)
ini_write_real("VAR","90",global.dnix)
ini_write_real("VAR","91",global.b3)
ini_write_real("VAR","92",global.dork)
ini_write_real("VAR","93",global.dwox1)
ini_write_real("VAR","94",global.xp)
ini_write_real("VAR","95",global.pro)
ini_write_real("VAR","96",global.wyst)
ini_write_real("VAR","97",global.suwy)
ini_write_real("VAR","98",global.atak)
ini_write_real("VAR","99",global.obro)
ini_write_real("VAR","100",global.zamki)
ini_write_real("VAR","101",global.ukowal)
ini_write_real("VAR","102",global.kradz)
ini_write_real("VAR","103",global.nmmap)
ini_write_real("VAR","104",global.umiecz)
ini_write_real("VAR","105",global.ubranyluk)
ini_write_real("VAR","106",global.zwm)
ini_write_real("VAR","107",global.mieczzn1)
ini_write_real("VAR","108",global.wini)
ini_write_real("VAR","109",global.rkrl)
ini_write_real("VAR","110",global.krlkon0)
ini_write_real("VAR","111",global.paypay)
ini_write_real("VAR","112",global.saygrl)
ini_write_real("VAR","113",global.notwow)
ini_write_real("VAR","114",global.normork)

if instance_exists(xXx)
{
	ini_write_real("VAR","115",xXx.x)
	ini_write_real("VAR","116",xXx.y)
}

if instance_exists(XXXs)
{
	ini_write_real("VAR","115",XXXs.x)
	ini_write_real("VAR","116",XXXs.y)
}

ini_write_real("VAR","117",global.firstlist)
ini_write_real("VAR","118",global.paykil)
ini_write_real("VAR","120",global.mis)
ini_close()


ini_open(string(global.savee)+"R"+string(room)+".ini")

with(all)
{
if ini_key_exists(string(global.savee)+"GAME",string(self.id))=0
ini_write_real(string(global.savee)+"GAME",string(self.id),1)
ini_write_real(string(global.savee)+"GAMEX",string(self.id),self.x)
ini_write_real(string(global.savee)+"GAMEY",string(self.id),self.y)
}

ini_close()

//instance_deactivate_all(1)
//instance_activate_object(nodeact)
}