// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function LOGAM(){

//instance_activate_all()

if file_exists(string(global.savee)+"R"+string(room)+".ini")
{
ini_open(string(global.savee)+"GLOBAL.ini")
global.owoll=ini_read_real("VAR","0",global.owoll)
global.pogter=ini_read_real("VAR","1",global.pogter)
global.take=ini_read_real("VAR","2",global.take)
global.NRDIAL=ini_read_real("VAR","3",global.NRDIAL)
global.grlw=ini_read_real("VAR","4",global.grlw)
global.day=ini_read_real("VAR","5",global.day)
global.dork=ini_read_real("VAR","6",global.dork)
global.zwm=ini_read_real("VAR","7",global.zwm)
global.cie=ini_read_real("VAR","8",global.cie)
global.zwzb=ini_read_real("VAR","9",global.zwzb)
global.pay=ini_read_real("VAR","10",global.pay)
global.dork=ini_read_real("VAR","11",global.dork)
global.rozm=ini_read_string("VAR","12",global.rozm)
global.hour=ini_read_real("VAR","13",global.hour)
global.day=ini_read_real("VAR","14",global.day)
global.job=ini_read_string("VAR","15",global.job)
global.inte=ini_read_string("VAR","16",global.inte)
global.minute=ini_read_real("VAR","17",global.minute)
global.jablka=ini_read_real("VAR","18",global.jablka)
global.zalrom=ini_read_real("VAR","19",global.zalrom)
global.fug=ini_read_real("VAR","20",global.fug)
global.tgo=ini_read_real("VAR","21",global.tgo)
global.zboze=ini_read_real("VAR","22",global.zboze)
global.jagody=ini_read_real("VAR","23",global.jagody)
global.grzyby=ini_read_real("VAR","24",global.grzyby)
global.dwox=ini_read_real("VAR","25",global.dwox)
global.zloto=ini_read_real("VAR","26",global.zloto)
global.ryby=ini_read_real("VAR","27",global.ryby)
global.woda=ini_read_real("VAR","28",global.woda)
global.srys=ini_read_real("VAR","29",global.srys)
global.cgame=ini_read_real("VAR","30",global.cgame)
global.gamefin=ini_read_real("VAR","31",global.gamefin)
global.krold=ini_read_real("VAR","32",global.krold)
global.magd=ini_read_real("VAR","33",global.magd)
global.wybmis=ini_read_real("VAR","34",global.wybmis)
global.peopatak=ini_read_real("VAR","35",global.peopatak)
global.kufopn=ini_read_real("VAR","36",global.kufopn)
global.otb=ini_read_real("VAR","37",global.otb)
global.skumj=ini_read_real("VAR","38",global.skumj)
global.paczk0=ini_read_real("VAR","39",global.paczk0)
global.pr1=ini_read_real("VAR","40",global.pr1)
global.fjask0=ini_read_real("VAR","41",global.fjask0)
global.worki=ini_read_real("VAR","42",global.worki)
global.lkey=ini_read_real("VAR","43",global.lkey)
global.nasi0=ini_read_real("VAR","44",global.nasi0)
global.zwmi1=ini_read_real("VAR","45",global.zwmi1)
global.artef0=ini_read_real("VAR","46",global.artef0)
global.ksiz1=ini_read_real("VAR","47",global.ksiz1)
global.stmo=ini_read_real("VAR","48",global.stmo)
global.pir=ini_read_real("VAR","49",global.pir)
global.drems1=ini_read_real("VAR","50",global.drems1)
global.mmp=ini_read_real("VAR","51",global.mmp)
global.zowce=ini_read_real("VAR","52",global.zowce)
global.wor2=ini_read_real("VAR","53",global.wor2)
global.worx1=ini_read_real("VAR","54",global.worx1)
//global.target=ini_read_string("VAR","55",global.target)
global.PTer=ini_read_real("VAR","56",global.PTer)
global.bowall1=ini_read_real("VAR","57",global.bowall1)
global.b1=ini_read_real("VAR","58",global.b1)
global.b2=ini_read_real("VAR","59",global.b2)
global.aczar=ini_read_real("VAR","60",global.aczar)
global.nozs=ini_read_real("VAR","61",global.nozs)
global.zlomiecze=ini_read_real("VAR","62",global.zlomiecze)
global.bdmiecze=ini_read_real("VAR","63",global.bdmiecze)
global.dmiecze=ini_read_real("VAR","64",global.dmiecze)
global.doluki=ini_read_real("VAR","65",global.doluki)
global.zupy=ini_read_real("VAR","66",global.zupy)
global.umieso=ini_read_real("VAR","67",global.umieso)
global.skory=ini_read_real("VAR","68",global.skory)
global.zbr1=ini_read_real("VAR","69",global.zbr1)
global.zbr2=ini_read_real("VAR","70",global.zbr2)
global.zbr3=ini_read_real("VAR","71",global.zbr3)
global.smetal=ini_read_real("VAR","72",global.smetal)
global.pulapka=ini_read_real("VAR","73",global.pulapka)
global.atakON=ini_read_real("VAR","74",global.atakON)
global.chleb=ini_read_real("VAR","75",global.chleb)
global.jkey=ini_read_real("VAR","76",global.jkey)
global.strdl=ini_read_real("VAR","77",global.strdl)
global.zmiecze=ini_read_real("VAR","78",global.zmiecze)
global.luki=ini_read_real("VAR","79",global.luki)
global.ter=ini_read_real("VAR","80",global.ter)
global.IN=ini_read_real("VAR","81",global.IN)
global.maata=ini_read_real("VAR","82",global.maata)
global.tgo=ini_read_real("VAR","83",global.tgo)
global.fug=ini_read_real("VAR","84",global.fug)
global.mzupa=ini_read_real("VAR","85",global.mzupa)
global.smieso=ini_read_real("VAR","86",global.smieso)
global.ryby=ini_read_real("VAR","87",global.ryby)
global.dbax=ini_read_real("VAR","88",global.dbax)
global.dwox=ini_read_real("VAR","89",global.dwox)
global.dnix=ini_read_real("VAR","90",global.dnix)
global.b3=ini_read_real("VAR","91",global.b3)
global.dork=ini_read_real("VAR","92",global.dork)
global.dwox1=ini_read_real("VAR","93",global.dwox1)
global.xp=ini_read_real("VAR","94",global.xp)
global.pro=ini_read_real("VAR","95",global.pro)
global.wyst=ini_read_real("VAR","96",global.wyst)
global.suwy=ini_read_real("VAR","97",global.suwy)
global.atak=ini_read_real("VAR","98",global.atak)
global.obro=ini_read_real("VAR","99",global.obro)
global.zamki=ini_read_real("VAR","100",global.zamki)
global.ukowal=ini_read_real("VAR","101",global.ukowal)
global.kradz=ini_read_real("VAR","102",global.kradz)
global.nmmap=ini_read_real("VAR","103",global.nmmap)
global.umiecz=ini_read_real("VAR","104",global.umiecz)
global.ubranyluk=ini_read_real("VAR","105",global.ubranyluk)
global.zwm=ini_read_real("VAR","106",global.zwm)
global.mieczzn1=ini_read_real("VAR","107",0)
global.wini=ini_read_real("VAR","108",0)
global.rkrl=ini_read_real("VAR","109",0)
global.krlkon0=ini_read_real("VAR","110",global.krlkon0)
global.paypay=ini_read_real("VAR","111",global.paypay)
global.saygrl=ini_read_real("VAR","112",global.saygrl)
global.notwow=ini_read_real("VAR","113",global.notwow)
global.normork=ini_read_real("VAR","114",global.normork)

if instance_exists(xXx)
{
	xXx.x=ini_read_real("VAR","115",xXx.x)
	xXx.y=ini_read_real("VAR","116",xXx.y)
}

if instance_exists(XXXs)
{
	XXXs.x=ini_read_real("VAR","115",XXXs.x)
	XXXs.y=ini_read_real("VAR","116",XXXs.y)
}

global.firstlist=ini_read_real("VAR","117",global.firstlist)
global.paykil=ini_read_real("VAR","118",global.paykil)
global.mis=ini_read_real("VAR","120",global.mis)

ini_close()

/*
with(all)
{
ini_open(string(global.savee)+"R"+string(room)+".ini")
var exi=ini_read_real(string(global.savee)+"GAME",string(self.id),1)
self.x=ini_read_real(string(global.savee)+"GAMEX",string(self.id),self.x)
self.y=ini_read_real(string(global.savee)+"GAMEY",string(self.id),self.y)
ini_close()
if exi=0 instance_destroy(self)
}*/
}

//instance_deactivate_all(1)
//instance_activate_object(nodeact)
}